[package]
name = "chip8-interpreter"
version = "0.1.0"
authors = ["Nick Martinez <habbarazzer@gmail.com>"]

[dependencies]
rand = "0.3"
gdk = "0.6.0"

[dependencies.gtk]
version = "0.2.0"
features = ["v3_10"]
